wechat:
  user: XDean
  app-id: ENC~GtBlP0j50TWm3+G3gB+4jjH3NcbGI5HIh2C0FD4H1lkumjMX
  app-secret: ENC~2cJ5xtNNQDW1Vm39deMzGttXNV1rMNbpPXXMC0p35nAZU9CglnOx2w==
admin:
  username: XDean
  password: ENC~upbs5xX+jwYyVKolYkoysvqo3h6pyjYM+Pf/L6//GeuPV+kSAoYu