spring:
  datasource:
    url: jdbc:h2:mem:test
    username: test
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
server:
  port: 0